### ISSUE TITLE
Some Tips

### ISSUE THREAD

**Issue by flpflan** [Reimuaa/reimuaa.github.io#1]
看到 up 主页说自己是 html beginner 所以提一下意见

像这种 page 比较多并且比较注重内容的网页最好用 **markdown** 而不是纯 **html** 写

我推荐部署一个个人博客比较好，可以找一些博客框架，比如`typecho` 或者 `hexo`，然后找一个现成的模板来用，网上搜一搜有很多

嫌部署麻烦也可以试试直接引用 markdown 解释器，然后文章内容存到 json 文件或者数据库里，用的时候 load 一下就行了（涉及到一些 javascript 知识，不过都学 html 了，javacsript 也算是必修）

**Comment by Reimuaa** [comment]
水平有限（）
我的主要精力还是放在写同人文上，这个只是我同人文的载体，高中生本身也没有那么多时间和精力研究这些，所以暂时没有升级的打算，目前来说还是看的过去的（）

**Comment by Reimuaa** [comment]
总之谢谢你意见，或许到大学比较有空了就会研究这些了吧（如果选计算机专业就是不得不研究了（X））
